# Generated by Django 3.0.3 on 2020-09-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chanllege',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('recommend', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='ExerciseTable',
        ),
        migrations.RemoveField(
            model_name='video',
            name='tag',
        ),
        migrations.AddField(
            model_name='video',
            name='tag_type',
            field=models.ManyToManyField(to='backend.TagDetail'),
        ),
        migrations.RemoveField(
            model_name='video',
            name='video_playlist',
        ),
        migrations.AddField(
            model_name='video',
            name='video_playlist',
            field=models.ManyToManyField(to='backend.VideoPlayList'),
        ),
    ]
