# Generated by Django 3.0.3 on 2020-09-14 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200914_1603'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseTable',
            fields=[
                ('videoplaylist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.VideoPlayList')),
                ('day', models.IntegerField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Chanllege')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('backend.videoplaylist',),
        ),
    ]
