# Generated by Django 3.0.3 on 2020-09-15 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200915_1546'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoPlaylists',
        ),
    ]
