# Generated by Django 3.0.3 on 2020-09-15 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_delete_videoplaylists'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPlaylists',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.VideoPlayList')),
                ('video', models.ManyToManyField(to='backend.Video')),
            ],
        ),
    ]
