# Generated by Django 3.0.3 on 2020-09-15 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_videoplaylists'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BMIUser',
        ),
    ]
