# Generated by Django 3.0.3 on 2020-09-15 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_bmiuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='BMIUser',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
