# Generated by Django 3.0.3 on 2020-09-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_bmiuser_userdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videoplaylist',
            old_name='playlistname',
            new_name='name',
        ),
        migrations.AddField(
            model_name='videoplaylist',
            name='video',
            field=models.ManyToManyField(to='backend.Video'),
        ),
        migrations.DeleteModel(
            name='VideoPlaylists',
        ),
    ]
