# Generated by Django 3.0.3 on 2020-09-29 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20200929_1516'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chanllege',
            new_name='Challenge',
        ),
    ]
