# Generated by Django 3.0.3 on 2020-09-29 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20200929_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoplaylist',
            name='video',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
