# Generated by Django 3.0.3 on 2020-09-29 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20200929_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('video', models.FileField(null=True, upload_to='videos/', verbose_name='Video File')),
                ('tag_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.TagDetail')),
            ],
        ),
        migrations.AddField(
            model_name='videoplaylist',
            name='video',
            field=models.ManyToManyField(to='backend.Video'),
        ),
    ]
