# Generated by Django 3.0.3 on 2020-09-30 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_auto_20200929_1557'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BMIUser',
        ),
    ]
