# Generated by Django 3.0.3 on 2020-10-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0019_auto_20201001_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.FileField(null=True, upload_to='videos/', verbose_name='Video Image'),
        ),
    ]
