# Generated by Django 3.0.3 on 2020-10-02 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0021_remove_userdetail_bmi'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDetail',
        ),
    ]
