# Generated by Django 3.0.3 on 2020-10-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_auto_20201002_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.FileField(null=True, upload_to='image/', verbose_name='Video Image'),
        ),
    ]
