# Generated by Django 3.0.3 on 2020-10-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0025_auto_20201004_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.FileField(null=True, upload_to='videos/', verbose_name='Video Image'),
        ),
    ]
