# Generated by Django 3.0.3 on 2020-10-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0026_auto_20201004_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoplaylist',
            name='image',
            field=models.FileField(null=True, upload_to='images', verbose_name='Playlist Image'),
        ),
    ]
